### PR TITLE
Restructure, cleanup and add new sections

### PR DESCRIPTION
**Pull request by johnsBeharry**
Updated the nav order, and moved some of the case study backend content to a new LSP section.

EDIT: note merging this includes unmerged work from @vindard [`feature/restructure-with-galoy`](https://github.com/peakshift/bitcoin-ux/tree/galoy-case-study) branch.

EDIT 2: Submarine Swaps page will be turned into a Payment Channel section at a later date, for now it may seem out of place after architecture.

### CODE REVIEW

**Review by vindard — CHANGES_REQUESTED** [review]
Just added two commits to fix some little things.

We should probably clean up some pages that look _really_ incomplete right now:
- `bolt.fun/pages/01_guide/40_routing/00_introduction.md`
- Add some sort of `incomplete` tag on the case studies pages

**Comment by johnsBeharry** [comment]
@vindard ye I forgot about that page, that was my link dump... maybe better to hide it? or leave it blank with just an intro?

**Comment by vindard** [comment]
> @vindard ye I forgot about that page, that was my link dump... maybe better to hide it? or leave it blank with just an intro?

Blank with intro makes sense, and then we could move those links to another page hidden from navigation

**Comment by johnsBeharry** [comment]
@vindard please see https://deploy-preview-39--boltfun.netlify.app/guide/routing

**Comment by vindard** [comment]
LGTM 🎉

**Pull request merged**
